name: Test custom GitHub Action

on:
  workflow_dispatch:
    inputs:
      country:
        description: Please type in name of country.
        required: true
        default: 'United States'

jobs:
  university_search_job:
    runs-on: ubuntu-latest
    name: A job to search by university
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
        
      - name: University search
        uses: ./
        id: search-university
        with:
          country: ${{ github.event.inputs.country }}
          
      - name: Get the output total
        run: echo "The total number of universities is ${{ steps.search-university.outputs.time }}"
